-- Fix premium_subscribers count: only count paid plans (not free)
create or replace view public.dashboard_metrics as
select
  (select count(*) from public.profiles) as total_users,
  (select count(*) from public.profiles where created_at > now() - interval '7 days') as new_users_week,
  (select count(*) from public.profiles where created_at > current_date) as new_users_today,
  (select count(*) from public.profiles where role = 'admin' or role = 'super_admin') as total_admins,
  (select count(*) from public.files where is_trashed = false) as total_files,
  (select count(*) from public.files where is_trashed = false and created_at > current_date) as today_uploads,
  (select count(*) from public.files where is_trashed = true) as total_trashed,
  (select count(*) from public.files where status = 'failed') as failed_uploads,
  (select coalesce(sum(storage_used_bytes), 0) from public.storage_quotas) as total_storage_bytes,
  (select coalesce(sum(storage_limit_bytes), 0) from public.storage_quotas) as total_limit_bytes,
  (select coalesce(sum(amount_fcfa), 0) from public.payments where status = 'paid') as total_revenue,
  (select coalesce(sum(amount_fcfa), 0) from public.payments where status = 'paid' and created_at > now() - interval '30 days') as monthly_revenue,
  (select count(*) from public.payments where status = 'paid' and created_at > current_date) as today_revenue_count,
  (select coalesce(sum(amount_fcfa), 0) from public.payments where status = 'paid' and created_at > current_date) as today_revenue_amount,
  (select count(*) from public.payments where status in ('failed', 'cancelled')) as failed_payments,
  (select count(*) from public.subscriptions s join public.storage_plans p on p.id = s.plan_id where s.is_active = true and s.is_trial = false and p.monthly_price_fcfa > 0) as premium_subscribers,
  (select count(*) from public.subscriptions where is_trial = true) as trial_users,
  (select count(*) from public.subscriptions where is_active = true) as total_active_subscriptions,
  (select count(*) from public.ai_events) as total_ai_requests,
  (select count(*) from public.ai_events where created_at > current_date) as today_ai_requests,
  (select coalesce(count(distinct user_id), 0) from public.activities where type = 'whatsapp_backup') as whatsapp_protected_users,
  (select coalesce(count(*), 0) from public.activities where type = 'whatsapp_backup' and created_at > current_date) as today_whatsapp_backups,
  (select count(*) from public.activities where created_at > current_date) as today_activities,
  (select count(*) from public.activities where type = 'signup' and created_at > current_date) as today_signups,
  (select count(*) from public.activities where type = 'login' and created_at > current_date) as today_logins,
  (select count(*) from public.activities where type = 'payment' and created_at > current_date) as today_payments;
